inherit_from: .rubocop_todo.yml
require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'bin/bundle'
    - 'config/**/**.rb'
    - 'spec/rails_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 250

Style/EmptyMethod:
  EnforcedStyle: expanded

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes

Style/AndOr:
  EnforcedStyle: conditionals

Layout/SpaceAroundOperators:
  EnforcedStyle: space

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Style/WordArray:
  EnforcedStyle: brackets